param(
  [string]$Collection = "material-symbols"
)

$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$assetDir = Join-Path $projectRoot "assets/ui/iconify"
$sourceDir = Join-Path $projectRoot "src/ui/icons"
$sourceFile = Join-Path $sourceDir "iconifyXml.ts"

New-Item -ItemType Directory -Force -Path $assetDir | Out-Null
New-Item -ItemType Directory -Force -Path $sourceDir | Out-Null

$iconMap = [ordered]@{
  "tabHome" = "home-rounded"
  "tabSearch" = "search-rounded"
  "tabList" = "format-list-bulleted-rounded"
  "tabLibrary" = "library-music-rounded"
  "navBack" = "arrow-back-rounded"
  "download" = "download-rounded"
  "cancel" = "cancel-rounded"
  "refresh" = "refresh-rounded"
  "delete" = "delete-outline-rounded"
}

$downloaded = [ordered]@{}

foreach ($entry in $iconMap.GetEnumerator()) {
  $name = $entry.Key
  $icon = $entry.Value
  $url = "https://api.iconify.design/$Collection/$icon.svg?download=1"
  $outputPath = Join-Path $assetDir "$name.svg"
  Invoke-WebRequest -Uri $url -OutFile $outputPath
  $xml = Get-Content -Raw -Path $outputPath
  $downloaded[$name] = $xml
  Write-Output "Downloaded: $name <= $Collection/$icon"
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Auto-generated by scripts/download-iconify-icons.ps1. Do not edit by hand.")
$lines.Add("")
$lines.Add("export const ICONIFY_XML = {")

foreach ($entry in $downloaded.GetEnumerator()) {
  $name = $entry.Key
  $jsonLiteral = $entry.Value | ConvertTo-Json -Compress
  $lines.Add("  ${name}: $jsonLiteral,")
}

$lines.Add("} as const;")
$lines.Add("")
$lines.Add("export type IconifyIconName = keyof typeof ICONIFY_XML;")
$lines.Add("")

$lines -join "`n" | Set-Content -Path $sourceFile -Encoding UTF8
Write-Output "Generated: $sourceFile"
